/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apollo.federation.java.tools;

import graphql.kickstart.tools.GraphQLQueryResolver;
import graphql.kickstart.tools.SchemaParser;
import graphql.schema.GraphQLSchema;

import java.util.List;

public class GraphQLSchemaLoader {

    public static GraphQLSchema load() {

        return SchemaParser.newParser()
                .file("schema.graphqls")
                .resolvers(new QueryResolver())
                .dictionary(User.class)
                .build()
                .makeExecutableSchema();
    }

    public static class QueryResolver implements GraphQLQueryResolver {
        public List<Product> allProducts() {
            return List.of();
        }
    }
}
